import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] })
export default function Home() {
  return (
    <>
      <Head>

        <title>Create next app </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />




      </Head>

      <main className={`${styles.main} ${inter.className}`} >
<h2> HELLO</h2>
      </main>
    </>


  );
}
